### ISSUE TITLE
Error in updated ver

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#122]
```
Python 3.6.6
Loading toolbar config
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/user/.cudatext/py/cuda_exttools/__init__.py", line 1, in <module>
    from .cd_exttools import Command
  File "/home/user/.cudatext/py/cuda_exttools/cd_exttools.py", line 134
    ''')
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0x95 in position 103: invalid start byte
```

**Comment by Alexey-T** [comment]
это форматирование точками?

**Comment by kvichans** [comment]
нет - это слетела кодировка: вместо UTF8 стало СР1251

fixed
