### ISSUE TITLE
Output panel navigation bug

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#146]
плохой С++ файл
```
#include <stdio.h>

int main(int argc, char *argv[])
{
  printf("Hello.\n"z);
  return 0; {
}
```

Тул такой
![Screenshot from 2021-07-24 15-23-50](https://user-images.githubusercontent.com/4154978/126868309-b2b02adf-08c1-4cd0-a1ce-95d1f316bb1c.png)

regex:
```
(?P<file>[\w\.\-]+):(?P<line>\d+):(?P<col>\d+):.+
```

крашится при навигации
```
Python 3.8.10
Init: cuda_exttools
Startup: 230ms, plugins: 100ms (exttools 103ms)
Init: cuda_new_file
Init: cuda_breadcrumbs
Init: cuda_console_complete
Init: cuda_hilite_occurrences
Init: cudatext
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_exttools/cd_exttools.py", line 689, in on_output_nav
    nav_ed  = _file_open(nav_file)
  File "/home/user/.config/cudatext/py/cuda_exttools/cd_exttools.py", line 2197, in _file_open
    if os.path.samefile(op_file, op_ed.get_filename()):
  File "/usr/lib/python3.8/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: ''
ERROR: Exception in CudaText for on_output_nav: FileNotFoundError: [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_exttools/cd_exttools.py", line 689, in on_output_nav
    nav_ed  = _file_open(nav_file)
  File "/home/user/.config/cudatext/py/cuda_exttools/cd_exttools.py", line 2197, in _file_open
    if os.path.samefile(op_file, op_ed.get_filename()):
  File "/usr/lib/python3.8/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: ''
ERROR: Exception in CudaText for on_output_nav: FileNotFoundError: [Errno 2] No such file or directory: ''
```

@halfbrained

**Comment by Alexey-T** [comment]
вывод тула на плохой файл
```
tst.cpp: In function ‘int main(int, char**)’:
tst.cpp:5:10: error: unable to find string literal operator ‘operator""z’ with ‘const char [8]’, ‘long unsigned int’ arguments
    5 |   printf("Hello.\n"z);
      |          ^~~~~~~~~~~
tst.cpp:7:1: error: expected ‘}’ at end of input
    7 | }
      | ^
tst.cpp:4:1: note: to match this ‘{’
    4 | {
      | ^

```

**Comment by halfbrained** [comment]
Очень интересно - ваш вариант у меня работает :) разбираюсь

**Comment by Alexey-T** [comment]
ого, у меня (после рестарта) заработало окей. хм.

**Comment by Alexey-T** [comment]
может влияет то что тогда- я поставил плагин, рестарт, сделал тул (без рестарта) и сразу запустил.

**Comment by halfbrained** [comment]
Это безымянный таб ломал, исправил

**Comment by Alexey-T** [comment]
теперь все ОК.
