### ISSUE TITLE
Tidy cannot run

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#19]
```
Python 3.4.3 (default, Oct 14 2015, 20:31:36) 
[GCC 4.8.4]
Command.run:500 nm="Tidy", cmnd="", ddir="tidy", prms_s="-errors -quiet "{FileName}""
Command.run:522 ready prms_l=['-errors', '-quiet', '/home/user/test-tree.html']
Command.run:525 val4call=['tidy', '-errors', '-quiet', '/home/user/test-tree.html']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/cuda/cuda/app/py/cuda_exttools/__init__.py", line 14, in run
    def run(self, ext_id):          return RLS.run(ext_id)
  File "/home/user/cuda/cuda/app/py/cuda_exttools/cd_exttools.py", line 530, in run
    subprocess.Popen(val4call, cwd=ddir)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: ''

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/cuda/cuda/app/py/cuda_exttools/__init__.py", line 14, in run
    def run(self, ext_id):          return RLS.run(ext_id)
  File "/home/user/cuda/cuda/app/py/cuda_exttools/cd_exttools.py", line 530, in run
    subprocess.Popen(val4call, cwd=ddir)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by Alexey-T** [comment]
![tid](https://cloud.githubusercontent.com/assets/4154978/11966656/245b10f4-a90e-11e5-8f25-2c1c0e0b93bc.png)

**Comment by kvichans** [comment]
fix
Ошибка из-за непонимания принципов вызова Popen. Убрал при вызове cwd, если init_folder пустой

**Comment by Alexey-T** [comment]
не раб.Не выводит ничего на плох. файле ни в output ни в таб

```
Command.run:523 val4call=['tidy', '-errors', '-quiet', '/home/user/test-tree.html']
```

**Comment by kvichans** [comment]
Как этот тул описан в exttools.json?

**Comment by Alexey-T** [comment]
пришлю

**Comment by kvichans** [comment]
Ага!
Замените в 527
`if 'Y'!=ext.get('rslt', 'N'):`
на
`if 'N'==ext.get('rslt', 'N'):`

**Comment by Alexey-T** [comment]
:)

**Comment by Alexey-T** [comment]
все равно не раб.

**Comment by Alexey-T** [comment]
Поставьте tidy ,pls

**Comment by kvichans** [comment]
Научите ставить tidy

**Comment by Alexey-T** [comment]
.exe скопировать в PATH- переменная в ОС, http://sourceforge.net/projects/synwrite-addons/files/Linters/linter.HtmlTidy.zip/download

**Comment by kvichans** [comment]
PATH зачем? Если я укажу полный путь exe в туле - нормально?

**Comment by kvichans** [comment]
Что сделать с linter.HtmlTidy.zip?

**Comment by Alexey-T** [comment]
- путь тоже нормально
- в моем zip лежит tidy.exe

**Comment by kvichans** [comment]
пробую...

**Comment by kvichans** [comment]
Воспроизвел

**Comment by kvichans** [comment]
Поправил (наошибался изрядно!)
tidy отрабатывает, но я включил "Shell cmd"

**Comment by Alexey-T** [comment]
Это не shell cmd,почему надо вкл?

**Comment by kvichans** [comment]
Как же не shell, если выдачу его я вижу в DOS-окне

**Comment by kvichans** [comment]
при установке "не shell" то же работает, только мелькает какое-то запущенное окно

**Comment by Alexey-T** [comment]
shell==запуск Вин ф-цией shellExecute. отличие не помню
