### ISSUE TITLE
err- New

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#28]
- Add...
- select any file e.g. project1.LPI
- OK(no fill other)

```
Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/cuda/cuda/app/py/cuda_exttools/__init__.py", line 13, in dlg_config
    def dlg_config(self):           return RLS.dlg_config()
  File "/home/user/cuda/cuda/app/py/cuda_exttools/cd_exttools.py", line 506, in dlg_config
    return self.dlg_config_list()
  File "/home/user/cuda/cuda/app/py/cuda_exttools/cd_exttools.py", line 209, in dlg_config_list
    self.last_ext_id    = ids[ext_ind]
IndexError: list index out of range
```

**Comment by Alexey-T** [comment]
потом так стало

![err](https://cloud.githubusercontent.com/assets/4154978/11986168/9df94046-a9dd-11e5-9279-4c9f938293f6.png)

**Comment by kvichans** [comment]
Воспроизводится

**Comment by kvichans** [comment]
fix
