### ISSUE TITLE
(bug) Clone

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#31]
list имеет 1 п-т.Жмем clone, clone. вылет

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/cuda/cuda/app/py/cuda_exttools/__init__.py", line 13, in dlg_config
    def dlg_config(self):           return RLS.dlg_config()
  File "/home/user/cuda/cuda/app/py/cuda_exttools/cd_exttools.py", line 269, in dlg_config
    return self.dlg_config_list()
  File "/home/user/cuda/cuda/app/py/cuda_exttools/cd_exttools.py", line 428, in dlg_config_list
    self.last_ext_id    = ids[ext_ind]
IndexError: list index out of range
```

**Comment by kvichans** [comment]
Выложил fix
