### ISSUE TITLE
Exception on run if cannot run

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#48]
создал тул--взял просто файл у него нет атрибута "можно запускать".Надо проверять это.А то вываливает

```

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_exttools/cd_exttools.py", line 247, in run
    subprocess.Popen(val4call, **nmargs)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```

**Comment by kvichans** [comment]
как это проверить?

**Comment by Alexey-T** [comment]
try:
subprocess.Popen()
except:
...

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
Не юзаете экзепшн?

**Comment by kvichans** [comment]
сейчас - нет

**Comment by kvichans** [comment]
Согласен - это нужно

**Comment by Alexey-T** [comment]
не сделано-хотя в Истории есть

**Comment by Alexey-T** [comment]
ловите  except ValueError as exc:
А у меня PermissionError: [Errno 13] Permission denied

**Comment by Alexey-T** [comment]
1-вое место вызова процесса

```
            try:
                subprocess.Popen(val4call, **nmargs)
            except Exception as ex:
                app.msg_box('{}: {}'.format(type(ex), ex), app.MB_OK)
            return
```

поправьте тут и второе место.

**Comment by kvichans** [comment]
fix

**Comment by Alexey-T** [comment]
не то- надо писать не ValueError -он толко один из эксепшенов-есть и другие их надо тоже ловить.

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
надо "Exception"

**Comment by kvichans** [comment]
да, так и сделал

**Comment by Alexey-T** [comment]
жду бету

**Comment by Alexey-T** [comment]
`<class 'PermissionError'>: [Errno 13] Permission denied`

можно показать так?
`PermissionError: [Errno 13] Permission denied`

**Comment by kvichans** [comment]
fix
