### ISSUE TITLE
Deleted tool, err

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#55]
создал тул с кривым файлом (чтобы была ошибка PermisError).
назначил его лексу С.
теперь удалил тул
теперь для С делаю run main tool--тут ошибка странная "No tool 34534"

теперь баг. диалог main tool не вызывается...

```
Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_exttools/cd_exttools.py", line 424, in dlg_config
    return self._dlg_config_list()
  File "/home/user/.cudatext/py/cuda_exttools/cd_exttools.py", line 576, in _dlg_config_list
    self._dlg_main_tool(0 if new_ext_ind==-1 else ids[new_ext_ind])
  File "/home/user/.cudatext/py/cuda_exttools/cd_exttools.py", line 676, in _dlg_main_tool
    for lxr in lxrs_l]
  File "/home/user/.cudatext/py/cuda_exttools/cd_exttools.py", line 676, in <listcomp>
    for lxr in lxrs_l]
KeyError: 195608
```

**Comment by kvichans** [comment]
ясно

**Comment by kvichans** [comment]
fix
