### ISSUE TITLE
Keyerror- dlg Maintool

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#57]
не вызывается длг MainToolFor

```

Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_exttools/cd_exttools.py", line 424, in dlg_config
    return self._dlg_config_list()
  File "/home/user/.cudatext/py/cuda_exttools/cd_exttools.py", line 581, in _dlg_config_list
    self._dlg_main_tool(0 if new_ext_ind==-1 else ids[new_ext_ind])
  File "/home/user/.cudatext/py/cuda_exttools/cd_exttools.py", line 684, in _dlg_main_tool
    for lxr in lxrs_l]
  File "/home/user/.cudatext/py/cuda_exttools/cd_exttools.py", line 684, in <listcomp>
    for lxr in lxrs_l]
KeyError: 195608
```

конфиг

[exttools.zip](https://github.com/kvichans/cuda_exttools/files/107863/exttools.zip)

**Comment by kvichans** [comment]
Да, подловили.
С-лексеру назначили главтул, а потом лексер деактивировали?

**Comment by Alexey-T** [comment]
Потом удалил тул

**Comment by kvichans** [comment]
Да, реализовал слишком оптимистично.
Правлю..

**Comment by kvichans** [comment]
fixed
Исправление происходит при загрузке плагина.
