### ISSUE TITLE
Dont work w/o plugin ProjMan

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#79]
On start (on adding menuitem):

```
Traceback (most recent call last):
  File "/home/user/.cudatext/py/cuda_exttools/cd_exttools.py", line 18, in <module>
    import cuda_project_man
ImportError: No module named 'cuda_project_man'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/user/.cudatext/py/cuda_exttools/__init__.py", line 1, in <module>
    from .cd_exttools import Command
  File "/home/user/.cudatext/py/cuda_exttools/cd_exttools.py", line 21, in <module>
    pass;                       LOG and log('No proj vars',())
NameError: name 'LOG' is not defined
```

**Comment by kvichans** [comment]
1. Todo
2. LOG - bug
