### ISSUE TITLE
bug: Fill option

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_exttools#97]
```
Python 3.4.3
Setting icons: AwOken_24x24
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_exttools/cd_exttools.py", line 672, in dlg_config
    url_url    = _subst_fltd_props(url_url, file_nm, cCrt, rCrt, ext['nm'], umcs=umc_vals, prjs=get_proj_vars())
UnboundLocalError: local variable 'ext' referenced before assignment
```

есть тул
http://google.com/search?q={SelectedText|q}
выделено "вввв"
включение галки Fill дает ошибку

**Comment by kvichans** [comment]
:( результат copy+paste
